In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/raw/jobs.csv")
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Easy Apply
0,0,"Data Analyst, Center on Immigration and Justic...",$37K-$66K (Glassdoor est.),Are you eager to roll up your sleeves and harn...,3.2,Vera Institute of Justice\n3.2,"New York, NY","New York, NY",201 to 500 employees,1961,Nonprofit Organization,Social Assistance,Non-Profit,$100 to $500 million (USD),-1,True
1,1,Quality Data Analyst,$37K-$66K (Glassdoor est.),Overview\n\nProvides analytical and technical ...,3.8,Visiting Nurse Service of New York\n3.8,"New York, NY","New York, NY",10000+ employees,1893,Nonprofit Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,-1
2,2,"Senior Data Analyst, Insights & Analytics Team...",$37K-$66K (Glassdoor est.),We’re looking for a Senior Data Analyst who ha...,3.4,Squarespace\n3.4,"New York, NY","New York, NY",1001 to 5000 employees,2003,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,GoDaddy,-1
3,3,Data Analyst,$37K-$66K (Glassdoor est.),Requisition NumberRR-0001939\nRemote:Yes\nWe c...,4.1,Celerity\n4.1,"New York, NY","McLean, VA",201 to 500 employees,2002,Subsidiary or Business Segment,IT Services,Information Technology,$50 to $100 million (USD),-1,-1
4,4,Reporting Data Analyst,$37K-$66K (Glassdoor est.),ABOUT FANDUEL GROUP\n\nFanDuel Group is a worl...,3.9,FanDuel\n3.9,"New York, NY","New York, NY",501 to 1000 employees,2009,Company - Private,Sports & Recreation,"Arts, Entertainment & Recreation",$100 to $500 million (USD),DraftKings,True

In [4]:
df = df.drop("Unnamed: 0", axis=1)

In [5]:
df["Founded"] = pd.to_numeric(df["Founded"], errors="coerce")

In [6]:
df["Size"] = df["Size"].str.replace(" employees", "")

In [7]:
df["Revenue"] = df["Revenue"].str.replace(" USD", "")

In [8]:
df["Easy Apply"] = df["Easy Apply"].notnull().astype(int)

In [9]:
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         1
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
Easy Apply           0
dtype: int64

In [10]:
skills_list = [
    "python", "sql", "excel", "power bi", "tableau",
    "machine learning", "deep learning", "nlp",
    "aws", "azure", "gcp",
    "pandas", "numpy", "matplotlib", "seaborn"
]

In [11]:
def extract_skills(text):
    text = str(text).lower()
    found_skills = []
    
    for skill in skills_list:
        if skill in text:
            found_skills.append(skill)
    
    return found_skills

In [12]:
df["Skills"] = df["Job Description"].apply(extract_skills)

In [13]:
df[["Job Title", "Skills"]].head()

,Job Title,Skills
0,"Data Analyst, Center on Immigration and Justic...","[python, sql, aws]"
1,Quality Data Analyst,"[sql, excel]"
2,"Senior Data Analyst, Insights & Analytics Team...","[python, sql, excel, tableau]"
3,Data Analyst,"[sql, tableau, aws]"
4,Reporting Data Analyst,"[python, sql, excel]"

In [14]:
df_exploded = df.explode("Skills")

In [15]:
top_skills = df_exploded["Skills"].value_counts()
print(top_skills.head(10))

Skills
sql                 1389
excel               1354
python               637
tableau              620
aws                  275
machine learning     180
power bi             180
azure                 64
pandas                41
numpy                 23
Name: count, dtype: int64

In [16]:
df.to_csv("../data/processed/cleaned_jobs.csv", index=False)
df_exploded.to_csv("../data/processed/skills_data.csv", index=False)

In [17]:
df.to_csv("../data/processed/cleaned_jobs_fixed.csv", index=False, encoding='utf-8')

In [ ]:
pip install streamlit plotly pandas

: